import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Doge Clicker | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col">
          <div className="h-[88vh]"> {children}</div>
        </div>
        <NavBar></NavBar>
      </body>
    </html>
  );
}
